import type { CamPose, StoryDef } from '../../story/types'
import TechniqueScene from './Scene'
import TechniqueExplore from './Explore'
import { FRAME_OPTS, PAD } from './layout'
import { seedExplore } from './exploreStore'
// the spoken explanation, one paragraph per beat (narration.json; generated by scripts/narration-manifest.mjs, H.75)
import narration from './narration.gen'

/* =========================================================================
   08 TECHNIQUE: Greg Glassman's essay "Technique" (CrossFit Level 1 Training
   Guide pp. 40-44; STORYBOARD-technique.md). One argument in ten beats, in
   the article's order: judge a program by safety, efficacy and efficiency;
   they point one way but trade off; measuring work makes how you move
   matter; the graph that defines technique; what a deviation is; the
   charter; speed is not the enemy; threshold training; the worked example
   (signature); technique is everything.

   Beat copy lives here so a reviewer can check every `source` against
   fitnessData.ts (the existing exports and the four article blocks of
   STORYBOARD-technique 7.2). Titles <= 30 characters, bodies <= 140, plain
   hyphens; quotes verbatim and one sentence at most; every number on screen
   is the article's own. No narration yet (it is written and recorded
   separately), so the chapter declares none and has no sound (H.72).

   Camera: one pose for every beat and for explore (L6: every subject is
   flat; the athlete is a side view in the chart plane): exactly front-on
   with the telephoto fov 22, fitting the chapter's engine-owned chart frame
   inside the focus rect, label room in the padding. Beats hand off inside
   the frame (fades and FLIPs), never with a pan.
   ========================================================================= */

const CHART: CamPose = {
  target: (_l, f) => [(f.box[0][0] + f.box[1][0]) / 2, (f.box[0][1] + f.box[1][1]) / 2, 0],
  az: 0,
  el: 0,
  fov: 22,
  fit: (_l, f) => f.box,
  padPx: PAD,
}

export const techniqueStory: StoryDef = {
  key: 'technique',
  narration,
  frame: FRAME_OPTS,
  beats: [
    {
      id: 'judge',
      title: 'Return, rate, finish line',
      body: 'Judge a program by evidence: efficacy is the return, efficiency its time rate, safety how many people end up at the finish line.',
      source: 'fitnessData.SEE + fitnessData.TECHNIQUE_SEE',
      terms: { efficacy: 'yellowGreen', efficiency: 'practiced', safety: 'phosphagen' },
      build: 6.0,
      // the three lane names, WORK CAPACITY, the four ticks and 2 OF 10, read after the build
      sceneWords: 12,
      cam: { L: CHART },
    },
    {
      id: 'vectors',
      title: 'Three vectors, one direction',
      body: 'All three point the same way, yet trade off: intensity can compromise safety; losing people damages efficacy.',
      source: 'fitnessData.SEE_VECTORS + fitnessData.TECHNIQUE_SEE',
      terms: { Safety: 'phosphagen', efficacy: 'yellowGreen', efficiency: 'practiced', intensity: 'both' },
      build: 6.0,
      // the three names, SAME DIRECTION and the last trade-off's tick
      sceneWords: 7,
      cam: { L: CHART },
    },
    {
      id: 'quality',
      title: 'Quantity needs quality',
      body: 'Measured by work capacity, movement matters: mechanics is physics, technique the method, form good or bad, style a signature.',
      source: 'fitnessData.TECHNIQUE_SEE + fitnessData.TECHNIQUE_TERMS',
      build: 5.0,
      // HOW YOU MOVE, the four callouts and NO BEARING
      sceneWords: 10,
      cam: { L: CHART },
    },
    {
      id: 'graph',
      title: 'Technique, defined',
      body: 'Plot work accomplished against energy expended. Technique is what maximizes the work completed for the energy expended.',
      source: 'fitnessData.CHARTER + fitnessData.TECHNIQUE_GRAPH',
      build: 5.5,
      // the axis titles, INEFFICIENT, IDEAL and the claim
      sceneWords: 6,
      cam: { L: CHART },
    },
    {
      id: 'deviation',
      title: 'What a deviation is',
      body: 'Form judged bad. One lifter pops the hip and gets under it; the other pulls with a rounded back. To stay safe, use good form.',
      source: 'fitnessData.TECHNIQUE_TERMS + fitnessData.TECHNIQUE_GRAPH',
      terms: { 'rounded back': 'sick' },
      build: 6.0,
      // ROUNDED BACK and GOOD TECHNIQUE, GOOD FORM (plus the two passing names)
      sceneWords: 9,
      cam: { L: CHART },
    },
    {
      id: 'charter',
      title: 'The charter',
      body: 'Mechanics, consistency, then and only then intensity. Ignoring this order increases the risk for injury, especially under load.',
      source: 'fitnessData.CHARTER + fitnessData.MCI_SKIP_PENALTY',
      terms: { intensity: 'both', injury: 'sick' },
      build: 5.5,
      // the axis titles, the three bands, ONLY THEN and RISK FOR INJURY
      sceneWords: 9,
      cam: { L: CHART },
    },
    {
      id: 'odds',
      title: 'Not at odds',
      body: 'Proficiency comes with speed: a perfectly exquisite Fran is worthless if it takes 32 minutes. Technique versus speed is an illusion.',
      source: 'fitnessData.THRESHOLD + fitnessData.TECHNIQUE_SPEED',
      build: 5.5,
      // the plane's titles, the target, the two examples, the either-or and the claim
      sceneWords: 14,
      cam: { L: CHART },
    },
    {
      id: 'threshold',
      title: 'Threshold training',
      body: 'When the movement starts falling apart, do not slow down: fix it at that speed. Errors broaden, then shrink without slowing.',
      source: 'fitnessData.THRESHOLD + fitnessData.TECHNIQUE_SPEED',
      terms: { 'falling apart': 'sick' },
      build: 6.5,
      // FALLING APART, FIX IT AT THAT SPEED and THRESHOLD TRAINING
      sceneWords: 8,
      cam: { L: CHART },
    },
    {
      id: 'margin',
      title: 'Advance the margin',
      body: 'Perfect at 10,000 foot-pounds per minute, falling apart at 12,000: train that band until 12,000 is great. Next target: 14,000.',
      source: 'fitnessData.THRESHOLD',
      build: 6.5,
      // the signature beat (A.3): the margin advanced past 14,000 holds at least 4 s
      signature: true,
      sceneWords: 9,
      cam: { L: CHART },
      impact: [0.82, 0.94],
    },
    {
      id: 'everything',
      title: 'Technique is everything',
      body: 'Without it you will not express power in significant measure, or be safe in trying. It is part of safety, efficacy and efficiency.',
      source: 'fitnessData.TECHNIQUE_SPEED + fitnessData.SEE_VECTORS',
      terms: { safety: 'phosphagen', efficacy: 'yellowGreen', efficiency: 'practiced' },
      build: 5.0,
      // the axis titles, TECHNIQUE, the three-swatch legend and the claim
      sceneWords: 7,
      cam: { L: CHART },
    },
  ],
  Scene: TechniqueScene,
  Explore: TechniqueExplore,
  explore: {
    cam: { L: CHART },
    limits: { az: [-15, 15], el: [0, 10], zoom: [0.85, 1.3] },
    initFromBeat(i) {
      seedExplore(i)
    },
  },
}

export default techniqueStory
