// GENERATED by scripts/narration-manifest.mjs from narration.json and public/narration/fitness/intro/. Never edit
// by hand: change narration.json, regenerate the clips it names (the voice/ pipeline), copy them into
// public/narration/fitness/intro/ and run `node scripts/narration-manifest.mjs` (DESIGN.md I.6.5, H.72).
import type { StoryNarration } from '../../story/types'

const narration: StoryNarration = {
  title: {
    beat: 'title',
    text: 'What is fitness? In the CrossFit Journal, in October two thousand two, Greg Glassman set out to do what he argued no authority had bothered to do: give a clear, usable, measurable definition of fitness.',
    hash: 'a3d87a62f8',
    file: 'narration/fitness/intro/title-a3d87a62f8.mp3',
    dur: 12.809,
    speech: [[0.12, 1.22], [1.936, 12.693]],
    words: 35,
    maxGap: 0.716,
    lufs: -17.4,
    tp: -3,
    sync: [[0.35, 0.96], [0.4, 9.056], [0.85, 12.028], [1, 12.369]],
  },
  models: {
    beat: 'models',
    text: 'He built it from four complementary models and one definition. First, ten general physical skills. Then the hopper, a drum of random challenges. Three metabolic engines, the energy systems. And a continuum, from sickness, through wellness, to fitness.',
    hash: '9f510d8373',
    file: 'narration/fitness/intro/models-9f510d8373.mp3',
    dur: 18.11,
    speech: [[0.123, 6.927], [7.316, 17.998]],
    words: 38,
    maxGap: 0.389,
    lufs: -17.9,
    tp: -3.2,
    sync: [[0.001, 2.521], [0.12, 4.242], [0.27, 6.403], [0.32, 6.653], [0.5, 8.885], [0.52, 10.676], [0.67, 13.187], [0.72, 14.088], [0.87, 15.708], [1, 16.669]],
  },
  definition: {
    beat: 'definition',
    text: 'And the definition: fitness is work capacity across broad time and modal domains. Plot power output against the duration of the effort. Average it across many tasks, and the area under the resulting curve is your fitness.',
    hash: 'ba0b4b6d90',
    file: 'narration/fitness/intro/definition-ba0b4b6d90.mp3',
    dur: 13.558,
    speech: [[0.123, 13.454]],
    words: 37,
    maxGap: 0.21,
    lufs: -17.2,
    tp: -3.7,
    sync: [[0.15, 2.944], [0.3, 6.228], [0.42, 7.73], [0.68, 10.413], [0.7, 11.245], [0.95, 12.736], [1, 13.207]],
  },
  lifetime: {
    beat: 'lifetime',
    text: 'Now add a whole life. Stretch that curve back through every age, and it becomes a surface. Sustain that capacity across a lifetime, and it is health: the volume you keep under the surface.',
    hash: '8a9a75aecb',
    file: 'narration/fitness/intro/lifetime-8a9a75aecb.mp3',
    dur: 11.797,
    speech: [[0.122, 5.425], [5.98, 9.306], [9.702, 11.683]],
    words: 34,
    maxGap: 0.555,
    lufs: -18.6,
    tp: -3,
    sync: [[0.1, 1.863], [0.7, 4.987], [0.75, 8.543], [1, 10.956]],
  },
  map: {
    beat: 'map',
    text: 'This lesson walks through each model, as presented in the original article and the official CrossFit Level 1 Training Guide. Skills, the hopper, energy, capacity, the continuum, and health. Six interactive models. Pick any one to begin.',
    hash: '250c29cf38',
    file: 'narration/fitness/intro/map-250c29cf38.mp3',
    dur: 16.365,
    speech: [[0.138, 6.896], [7.289, 12.802], [13.296, 16.248]],
    words: 37,
    maxGap: 0.494,
    lufs: -18.6,
    tp: -2.4,
    sync: [[0.06, 4.147], [0.085, 5.028], [0.25, 7.351], [0.34, 8.312], [0.43, 9.274], [0.51, 10.195], [0.52, 11.297], [0.69, 12.419], [1, 13.961]],
  },
}

export default narration
