import type { Box, CamPose, StoryDef, V3 } from '../../story/types'
import CrossfitScene from './Scene'
import CrossfitExplore from './Explore'
import CrossfitHud from './Hud'
import { CHART_PAD, FRAME_OPTS, padBox, pair, pairKind, pyrBox, table, tableKind, tilesBox, tilesKind } from './layout'
import { frameFor } from '../../story/kit/chartFrame'
import { seedExplore } from './exploreStore'
// the spoken explanation, one paragraph per beat (narration.json; generated by scripts/narration-manifest.mjs, H.75)
import narration from './narration.gen'

/* =========================================================================
   07 CROSSFIT: "The prescription and the pyramid" (STORYBOARD-crossfit.md).
   Beat copy lives here so a reviewer can check every `source` against
   fitnessData.ts (the Module 07 data and the 2026-10-01 research section).
   Titles <= 30 characters, bodies <= 140, plain hyphens, quotes verbatim and
   one sentence at most; computed values live in labels and the HUD only.
   No narration yet (it is written and recorded separately), so the chapter
   declares none and has no sound (H.72).

   Camera: every station is read front-on (az 0, el 0), the charts with the
   telephoto fov 22 (L12); the pyramid is a solid, so it is seen from a
   decisive oblique (L6: a new dimension) and the camera holds it from C5 to
   the end. Each station's fit is the box its current arrangement builds
   (portrait or wide, layout.ts), so the camera and the geometry agree.
   ========================================================================= */

const center = (b: Box): V3 => [(b[0][0] + b[1][0]) / 2, (b[0][1] + b[1][1]) / 2, (b[0][2] + b[1][2]) / 2]

const tilesFit = (): Box => tilesBox(tilesKind())
const TILES: CamPose = { target: () => center(tilesFit()), az: 0, el: 0, fov: 26, fit: tilesFit, padPx: { l: 8, r: 8, t: 10, b: 10 } }

const pairFit = (): Box => padBox(pair(pairKind()).box, 0.2, 0.2, 0.3, 0.2)
const PAIR: CamPose = { target: () => center(pairFit()), az: 0, el: 0, fov: 24, fit: pairFit, padPx: { l: 12, r: 12, t: 14, b: 66 } }

const tableFit = (): Box => table(tableKind()).box
const TABLE: CamPose = { target: () => center(tableFit()), az: 0, el: 0, fov: 24, fit: tableFit, padPx: { l: 8, r: 8, t: 24, b: 22 } }

/**
 * Read as a chart: exactly front-on with a telephoto fov (L12, H.21). The C3 and C4 chart has its
 * own frame (an explicit chart frame, not StoryDef.frame: the chapter's explore model is the
 * pyramid, and the engine's explore checks read StoryDef.frame as the explore subject).
 */
const CHART: CamPose = { target: [0, 0, 0], az: 0, el: 0, fov: 22, fit: () => frameFor(FRAME_OPTS).box, padPx: CHART_PAD }

const PYR_L: CamPose = { target: () => center(pyrBox('L')), az: -22, el: 18, fov: 28, fit: () => pyrBox('L'), padPx: { l: 24, r: 24, t: 30, b: 18 } }
const PYR_P: CamPose = { target: () => center(pyrBox('P')), az: -16, el: 20, fov: 28, fit: () => pyrBox('P'), padPx: { l: 10, r: 10, t: 30, b: 12 } }

export const crossfitStory: StoryDef = {
  key: 'crossfit',
  narration,
  beats: [
    {
      id: 'prescription',
      title: 'The prescription',
      body: 'CrossFit is "constantly varied, high-intensity functional movement." It aims to prepare you for the unknown and the unknowable.',
      source: 'fitnessData.CF_PRESCRIPTION (quote, aim) + fitnessData.CF_PILLARS',
      terms: { 'constantly varied': 'monostructural', 'high-intensity': 'both', 'functional movement': 'yellowGreen' },
      build: 5.0,
      // the tiles' names and plain words land through the build; the last tile's (7 words) are read after it
      sceneWords: 7,
      cam: { L: TILES },
    },
    {
      id: 'functional',
      title: 'Movements from life',
      body: 'Squatting is standing from a seated position; deadlifting is picking any object off the ground. Both move many joints at once.',
      source: 'fitnessData.CF_FUNCTIONAL_QUOTES (natural) + fitnessData.CF_FUNCTIONAL_NOTES (multiJoint)',
      build: 6.0,
      // SQUAT, DEADLIFT, MULTI-JOINT
      sceneWords: 3,
      cam: { L: PAIR },
    },
    {
      id: 'replaced',
      title: 'One joint, or many',
      body: 'Isolation moves work one joint at a time. CrossFit swapped them: lateral raise to push press, curl to pull-up, leg extension to squat.',
      source: 'fitnessData.CF_FUNCTIONAL_NOTES (oneJoint) + fitnessData.CF_FUNCTIONAL_QUOTES (replaced)',
      build: 6.5,
      // the two heads and the six names
      sceneWords: 14,
      cam: { L: TABLE },
    },
    {
      id: 'power',
      title: 'Intensity is power',
      body: 'Intensity is power, the variable most tied to adaptation. Fran\'s work is constant, so 4:30 to 2:45 is a 60% increase in power.',
      source: 'fitnessData.CF_PILLARS (intensity) + fitnessData.FRAN_TABLE',
      terms: { Intensity: 'both' },
      build: 6.5,
      // the work, two times, two powers, the workout and the claim
      sceneWords: 9,
      cam: { L: CHART },
      impact: [0.86, 0.98],
    },
    {
      id: 'varied',
      title: 'Routine is the enemy',
      body: 'Cycle only 5 to 7 miles and you test weak below 5 and above 7. Varied work widens the margins of exposure.',
      source: 'fitnessData.VARIANCE_RUT + fitnessData.CF_VARIANCE_NOTES (cycle, expand)',
      terms: { '5 to 7 miles': 'monostructural', weak: 'sick' },
      build: 6.0,
      // EXPOSURE, WEAK, WEAK and the claim
      sceneWords: 8,
      cam: { L: CHART },
    },
    {
      id: 'pyramid',
      title: 'Built from the bottom',
      body: 'Nutrition, then metabolic conditioning, gymnastics, weightlifting and throwing, and sport: from molecules to mastery.',
      source: 'fitnessData.HIERARCHY + fitnessData.CF_HIERARCHY_NOTES (order, flow)',
      terms: {
        Nutrition: 'seaGreen',
        'metabolic conditioning': 'monostructural',
        gymnastics: 'gymnastics',
        'weightlifting and throwing': 'weightlifting',
        sport: 'both',
      },
      build: 5.5,
      // the five levels and their roles
      sceneWords: 16,
      cam: { L: PYR_L, P: PYR_P, window: [0, 0.3] },
    },
    {
      id: 'deficiency',
      title: 'Everything above suffers',
      body: 'We do not deliberately order these components but nature will. A deficiency at one level makes every level above it suffer.',
      source: 'HIERARCHY_RULE',
      terms: { deficiency: 'sick' },
      build: 6.0,
      // the signature beat (A.3): the crushed level and the leaning stack hold at least 4 s
      signature: true,
      sceneWords: 6,
      cam: { L: PYR_L, P: PYR_P },
    },
    {
      id: 'hundred',
      title: 'Fitness in 100 words',
      body: 'Eat meat and vegetables. Lift, master gymnastics, bike, run, swim and row hard and fast. Mix them, keep it short and intense, play sports.',
      source: 'HUNDRED_WORDS',
      build: 6.5,
      // the five lines on the levels and the claim
      sceneWords: 17,
      cam: { L: PYR_L, P: PYR_P },
    },
  ],
  Scene: CrossfitScene,
  Explore: CrossfitExplore,
  Hud: CrossfitHud,
  explore: {
    cam: { L: PYR_L, P: PYR_P },
    limits: { az: [-40, 40], el: [-12, 22], zoom: [0.7, 1.5] },
    initFromBeat(i) {
      seedExplore(i)
    },
  },
}

export default crossfitStory
